title: Standard
icon: paragraph

status:
  draft:
    label: Entwurf
  unlisted:
    label: Unveröffentlicht
  listed:
    label: Veröffentlicht

tabs:
  content: tabs/blocks
  media: tabs/media
  meta: tabs/meta/site
